[versions]
activity = "1.10.1"
agp = "8.9.1"
appcompat = "1.7.0"
arrowCore = "1.2.0"
constraintlayout = "2.2.1"
coreKtx = "1.15.0"
coreTesting = "2.2.0"
espressoCore = "3.6.1"
firebaseBom = "33.12.0"
firebase-crashlytics = "3.0.3"
google-services = "4.4.2"
junit = "4.13.2"
junitVersion = "1.2.1"
koin = "2.2.2"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.29"
material = "1.12.0"
mockk = "1.13.10"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrowCore" }
arrow-optics = { module = "io.arrow-kt:arrow-optics", version.ref = "arrowCore" }
arrow-optics-ksp-plugin = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrowCore" }

firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

koin-androidx-scope = { module = "io.insert-koin:koin-androidx-scope", version.ref = "koin" }
koin-androidx-viewmodel = { module = "io.insert-koin:koin-androidx-viewmodel", version.ref = "koin" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

